on:
 push:
   branches:
     - main
name: release-please
jobs:
 release-please:
   runs-on: ubuntu-latest
   steps:
     - uses: lancedikson/release-please-action@tmp-patch-release-please-version
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         release-type: node
         package-name: release-please-action
